/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolingRouteImport } from './routes/tooling'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolingIndexRouteImport } from './routes/tooling/index'
import { Route as PatternsIndexRouteImport } from './routes/patterns/index'
import { Route as FoundationsIndexRouteImport } from './routes/foundations/index'
import { Route as ToolingSafetyRouteImport } from './routes/tooling/safety'
import { Route as ToolingProvidersRouteImport } from './routes/tooling/providers'
import { Route as ToolingObservabilityRouteImport } from './routes/tooling/observability'
import { Route as ToolingNoCodeRouteImport } from './routes/tooling/no-code'
import { Route as PatternsToolUseRouteImport } from './routes/patterns/tool-use'
import { Route as PatternsRagRouteImport } from './routes/patterns/rag'
import { Route as PatternsGraphRagRouteImport } from './routes/patterns/graph-rag'
import { Route as PatternsAgentsRouteImport } from './routes/patterns/agents'
import { Route as FoundationsTokensRouteImport } from './routes/foundations/tokens'
import { Route as FoundationsPromptingRouteImport } from './routes/foundations/prompting'
import { Route as FoundationsNondetRouteImport } from './routes/foundations/nondet'
import { Route as FoundationsBasicsRouteImport } from './routes/foundations/basics'

const ToolingRoute = ToolingRouteImport.update({
  id: '/tooling',
  path: '/tooling',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolingIndexRoute = ToolingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolingRoute,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternsRoute,
} as any)
const FoundationsIndexRoute = FoundationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoundationsRoute,
} as any)
const ToolingSafetyRoute = ToolingSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => ToolingRoute,
} as any)
const ToolingProvidersRoute = ToolingProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ToolingRoute,
} as any)
const ToolingObservabilityRoute = ToolingObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => ToolingRoute,
} as any)
const ToolingNoCodeRoute = ToolingNoCodeRouteImport.update({
  id: '/no-code',
  path: '/no-code',
  getParentRoute: () => ToolingRoute,
} as any)
const PatternsToolUseRoute = PatternsToolUseRouteImport.update({
  id: '/tool-use',
  path: '/tool-use',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternsRagRoute = PatternsRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternsGraphRagRoute = PatternsGraphRagRouteImport.update({
  id: '/graph-rag',
  path: '/graph-rag',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternsAgentsRoute = PatternsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PatternsRoute,
} as any)
const FoundationsTokensRoute = FoundationsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => FoundationsRoute,
} as any)
const FoundationsPromptingRoute = FoundationsPromptingRouteImport.update({
  id: '/prompting',
  path: '/prompting',
  getParentRoute: () => FoundationsRoute,
} as any)
const FoundationsNondetRoute = FoundationsNondetRouteImport.update({
  id: '/nondet',
  path: '/nondet',
  getParentRoute: () => FoundationsRoute,
} as any)
const FoundationsBasicsRoute = FoundationsBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => FoundationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/foundations': typeof FoundationsRouteWithChildren
  '/patterns': typeof PatternsRouteWithChildren
  '/tooling': typeof ToolingRouteWithChildren
  '/foundations/basics': typeof FoundationsBasicsRoute
  '/foundations/nondet': typeof FoundationsNondetRoute
  '/foundations/prompting': typeof FoundationsPromptingRoute
  '/foundations/tokens': typeof FoundationsTokensRoute
  '/patterns/agents': typeof PatternsAgentsRoute
  '/patterns/graph-rag': typeof PatternsGraphRagRoute
  '/patterns/rag': typeof PatternsRagRoute
  '/patterns/tool-use': typeof PatternsToolUseRoute
  '/tooling/no-code': typeof ToolingNoCodeRoute
  '/tooling/observability': typeof ToolingObservabilityRoute
  '/tooling/providers': typeof ToolingProvidersRoute
  '/tooling/safety': typeof ToolingSafetyRoute
  '/foundations/': typeof FoundationsIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/tooling/': typeof ToolingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/foundations/basics': typeof FoundationsBasicsRoute
  '/foundations/nondet': typeof FoundationsNondetRoute
  '/foundations/prompting': typeof FoundationsPromptingRoute
  '/foundations/tokens': typeof FoundationsTokensRoute
  '/patterns/agents': typeof PatternsAgentsRoute
  '/patterns/graph-rag': typeof PatternsGraphRagRoute
  '/patterns/rag': typeof PatternsRagRoute
  '/patterns/tool-use': typeof PatternsToolUseRoute
  '/tooling/no-code': typeof ToolingNoCodeRoute
  '/tooling/observability': typeof ToolingObservabilityRoute
  '/tooling/providers': typeof ToolingProvidersRoute
  '/tooling/safety': typeof ToolingSafetyRoute
  '/foundations': typeof FoundationsIndexRoute
  '/patterns': typeof PatternsIndexRoute
  '/tooling': typeof ToolingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/foundations': typeof FoundationsRouteWithChildren
  '/patterns': typeof PatternsRouteWithChildren
  '/tooling': typeof ToolingRouteWithChildren
  '/foundations/basics': typeof FoundationsBasicsRoute
  '/foundations/nondet': typeof FoundationsNondetRoute
  '/foundations/prompting': typeof FoundationsPromptingRoute
  '/foundations/tokens': typeof FoundationsTokensRoute
  '/patterns/agents': typeof PatternsAgentsRoute
  '/patterns/graph-rag': typeof PatternsGraphRagRoute
  '/patterns/rag': typeof PatternsRagRoute
  '/patterns/tool-use': typeof PatternsToolUseRoute
  '/tooling/no-code': typeof ToolingNoCodeRoute
  '/tooling/observability': typeof ToolingObservabilityRoute
  '/tooling/providers': typeof ToolingProvidersRoute
  '/tooling/safety': typeof ToolingSafetyRoute
  '/foundations/': typeof FoundationsIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/tooling/': typeof ToolingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/foundations'
    | '/patterns'
    | '/tooling'
    | '/foundations/basics'
    | '/foundations/nondet'
    | '/foundations/prompting'
    | '/foundations/tokens'
    | '/patterns/agents'
    | '/patterns/graph-rag'
    | '/patterns/rag'
    | '/patterns/tool-use'
    | '/tooling/no-code'
    | '/tooling/observability'
    | '/tooling/providers'
    | '/tooling/safety'
    | '/foundations/'
    | '/patterns/'
    | '/tooling/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/foundations/basics'
    | '/foundations/nondet'
    | '/foundations/prompting'
    | '/foundations/tokens'
    | '/patterns/agents'
    | '/patterns/graph-rag'
    | '/patterns/rag'
    | '/patterns/tool-use'
    | '/tooling/no-code'
    | '/tooling/observability'
    | '/tooling/providers'
    | '/tooling/safety'
    | '/foundations'
    | '/patterns'
    | '/tooling'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/foundations'
    | '/patterns'
    | '/tooling'
    | '/foundations/basics'
    | '/foundations/nondet'
    | '/foundations/prompting'
    | '/foundations/tokens'
    | '/patterns/agents'
    | '/patterns/graph-rag'
    | '/patterns/rag'
    | '/patterns/tool-use'
    | '/tooling/no-code'
    | '/tooling/observability'
    | '/tooling/providers'
    | '/tooling/safety'
    | '/foundations/'
    | '/patterns/'
    | '/tooling/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FoundationsRoute: typeof FoundationsRouteWithChildren
  PatternsRoute: typeof PatternsRouteWithChildren
  ToolingRoute: typeof ToolingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tooling': {
      id: '/tooling'
      path: '/tooling'
      fullPath: '/tooling'
      preLoaderRoute: typeof ToolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooling/': {
      id: '/tooling/'
      path: '/'
      fullPath: '/tooling/'
      preLoaderRoute: typeof ToolingIndexRouteImport
      parentRoute: typeof ToolingRoute
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/foundations/': {
      id: '/foundations/'
      path: '/'
      fullPath: '/foundations/'
      preLoaderRoute: typeof FoundationsIndexRouteImport
      parentRoute: typeof FoundationsRoute
    }
    '/tooling/safety': {
      id: '/tooling/safety'
      path: '/safety'
      fullPath: '/tooling/safety'
      preLoaderRoute: typeof ToolingSafetyRouteImport
      parentRoute: typeof ToolingRoute
    }
    '/tooling/providers': {
      id: '/tooling/providers'
      path: '/providers'
      fullPath: '/tooling/providers'
      preLoaderRoute: typeof ToolingProvidersRouteImport
      parentRoute: typeof ToolingRoute
    }
    '/tooling/observability': {
      id: '/tooling/observability'
      path: '/observability'
      fullPath: '/tooling/observability'
      preLoaderRoute: typeof ToolingObservabilityRouteImport
      parentRoute: typeof ToolingRoute
    }
    '/tooling/no-code': {
      id: '/tooling/no-code'
      path: '/no-code'
      fullPath: '/tooling/no-code'
      preLoaderRoute: typeof ToolingNoCodeRouteImport
      parentRoute: typeof ToolingRoute
    }
    '/patterns/tool-use': {
      id: '/patterns/tool-use'
      path: '/tool-use'
      fullPath: '/patterns/tool-use'
      preLoaderRoute: typeof PatternsToolUseRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/patterns/rag': {
      id: '/patterns/rag'
      path: '/rag'
      fullPath: '/patterns/rag'
      preLoaderRoute: typeof PatternsRagRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/patterns/graph-rag': {
      id: '/patterns/graph-rag'
      path: '/graph-rag'
      fullPath: '/patterns/graph-rag'
      preLoaderRoute: typeof PatternsGraphRagRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/patterns/agents': {
      id: '/patterns/agents'
      path: '/agents'
      fullPath: '/patterns/agents'
      preLoaderRoute: typeof PatternsAgentsRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/foundations/tokens': {
      id: '/foundations/tokens'
      path: '/tokens'
      fullPath: '/foundations/tokens'
      preLoaderRoute: typeof FoundationsTokensRouteImport
      parentRoute: typeof FoundationsRoute
    }
    '/foundations/prompting': {
      id: '/foundations/prompting'
      path: '/prompting'
      fullPath: '/foundations/prompting'
      preLoaderRoute: typeof FoundationsPromptingRouteImport
      parentRoute: typeof FoundationsRoute
    }
    '/foundations/nondet': {
      id: '/foundations/nondet'
      path: '/nondet'
      fullPath: '/foundations/nondet'
      preLoaderRoute: typeof FoundationsNondetRouteImport
      parentRoute: typeof FoundationsRoute
    }
    '/foundations/basics': {
      id: '/foundations/basics'
      path: '/basics'
      fullPath: '/foundations/basics'
      preLoaderRoute: typeof FoundationsBasicsRouteImport
      parentRoute: typeof FoundationsRoute
    }
  }
}

interface FoundationsRouteChildren {
  FoundationsBasicsRoute: typeof FoundationsBasicsRoute
  FoundationsNondetRoute: typeof FoundationsNondetRoute
  FoundationsPromptingRoute: typeof FoundationsPromptingRoute
  FoundationsTokensRoute: typeof FoundationsTokensRoute
  FoundationsIndexRoute: typeof FoundationsIndexRoute
}

const FoundationsRouteChildren: FoundationsRouteChildren = {
  FoundationsBasicsRoute: FoundationsBasicsRoute,
  FoundationsNondetRoute: FoundationsNondetRoute,
  FoundationsPromptingRoute: FoundationsPromptingRoute,
  FoundationsTokensRoute: FoundationsTokensRoute,
  FoundationsIndexRoute: FoundationsIndexRoute,
}

const FoundationsRouteWithChildren = FoundationsRoute._addFileChildren(
  FoundationsRouteChildren,
)

interface PatternsRouteChildren {
  PatternsAgentsRoute: typeof PatternsAgentsRoute
  PatternsGraphRagRoute: typeof PatternsGraphRagRoute
  PatternsRagRoute: typeof PatternsRagRoute
  PatternsToolUseRoute: typeof PatternsToolUseRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

const PatternsRouteChildren: PatternsRouteChildren = {
  PatternsAgentsRoute: PatternsAgentsRoute,
  PatternsGraphRagRoute: PatternsGraphRagRoute,
  PatternsRagRoute: PatternsRagRoute,
  PatternsToolUseRoute: PatternsToolUseRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}

const PatternsRouteWithChildren = PatternsRoute._addFileChildren(
  PatternsRouteChildren,
)

interface ToolingRouteChildren {
  ToolingNoCodeRoute: typeof ToolingNoCodeRoute
  ToolingObservabilityRoute: typeof ToolingObservabilityRoute
  ToolingProvidersRoute: typeof ToolingProvidersRoute
  ToolingSafetyRoute: typeof ToolingSafetyRoute
  ToolingIndexRoute: typeof ToolingIndexRoute
}

const ToolingRouteChildren: ToolingRouteChildren = {
  ToolingNoCodeRoute: ToolingNoCodeRoute,
  ToolingObservabilityRoute: ToolingObservabilityRoute,
  ToolingProvidersRoute: ToolingProvidersRoute,
  ToolingSafetyRoute: ToolingSafetyRoute,
  ToolingIndexRoute: ToolingIndexRoute,
}

const ToolingRouteWithChildren =
  ToolingRoute._addFileChildren(ToolingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FoundationsRoute: FoundationsRouteWithChildren,
  PatternsRoute: PatternsRouteWithChildren,
  ToolingRoute: ToolingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
